### ISSUE TITLE
err: "CustomEvent" is not defined at ~/lib/useEpochNumber

### ISSUE THREAD

**Issue by lveneris** [Conflux-Chain/react-hooks#4]
I was attempting to use the `useBalance` feature of the react hooks library for my next.js project when I encountered an error. Having reviewed the code, it uses a `new CustomEvent` constructor, but `CustomEvent` is not defined anywhere in the code. I don't know what it's supposed to be so I cannot fix it myself, but I hope one of the package maintainers knows, and I hope this issue is useful in bringing the problem to resolution.

**Comment by yqrashawn** [comment]
@Nytelife26 are you rendering things using node? Like build in gastby?
